name: Deploy application to k8s

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: techfood
  EKS_CLUSTER_NAME: eks-terraform-tech-food
  IMAGE_TAG: latest

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    outputs:
      image-uri: ${{ steps.build-image.outputs.image-uri }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image-uri=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up kubectl for EKS
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          kubectl delete namespace techfood --ignore-not-found=true
          kubectl wait --for=delete namespace/techfood --timeout=120s || true
          kubectl apply -f k8s/v1/tech-food-namespace.yaml

          sleep 5

          sed -i.bak "s|DOCKER_IMAGE_PLACEHOLDER|${{ needs.build.outputs.image-uri }}|g" k8s/v1/tech-food-deployment-v1.yaml
          kubectl apply -f k8s/v1/tech-food-configmap-v1.yaml
          kubectl apply -f k8s/v1/tech-food-db-secret-v1.yaml
          kubectl apply -f k8s/v1/tech-food-deployment-v1.yaml
          kubectl apply -f k8s/v1/tech-food-service-v1.yaml
          kubectl apply -f k8s/v1/tech-food-hpa-v1.yaml
